---
- name: Install Nginx on Target Machine
  hosts: web_servers  # Replace with the appropriate group or hostname in your inventory
  become: yes  # Runs tasks with sudo privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on Debian-based systems
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat-based systems
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes
